<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Bookings Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .status-paid {
            color: #28a745;
            font-weight: bold;
        }
        .status-pending {
            color: #ffc107;
            font-weight: bold;
        }
        .status-cancelled {
            color: #dc3545;
            font-weight: bold;
        }
        .amount {
            text-align: right;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .summary h3 {
            margin-top: 0;
            color: #333;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>E-Tiko Bookings Report</h1>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p><strong>Total Bookings:</strong> {{ $bookings->count() }}</p>
        <p><strong>Total Revenue:</strong> KSh {{ number_format($bookings->sum('amount'), 2) }}</p>
        <p><strong>Paid Bookings:</strong> {{ $bookings->where('status', 'PAID')->count() }}</p>
        <p><strong>Pending Bookings:</strong> {{ $bookings->where('status', 'PENDING')->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>User Name</th>
                <th>Event Name</th>
                <th>Ticket Type</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Booking Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $booking)
            <tr>
                <td>{{ $booking->booking_id }}</td>
                <td>{{ $booking->user_name }}</td>
                <td>{{ $booking->event_name }}</td>
                <td>{{ $booking->ticket_type }}</td>
                <td class="amount">KSh {{ number_format($booking->amount, 2) }}</td>
                <td>
                    @if($booking->status === 'PAID')
                        <span class="status-paid">{{ $booking->status }}</span>
                    @elseif($booking->status === 'PENDING')
                        <span class="status-pending">{{ $booking->status }}</span>
                    @else
                        <span class="status-cancelled">{{ $booking->status }}</span>
                    @endif
                </td>
                <td>{{ $booking->booking_date->format('M j, Y g:i A') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by E-Tiko Event Management System</p>
    </div>
</body>
</html>
