<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Revenue Report - {{ now()->format('F j, Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 5px;
            border: 1px solid #dee2e6;
        }
        .summary h3 {
            margin-top: 0;
            color: #333;
            border-bottom: 1px solid #dee2e6;
            padding-bottom: 10px;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }
        .summary-item {
            text-align: center;
        }
        .summary-value {
            font-size: 24px;
            font-weight: bold;
            color: #28a745;
        }
        .summary-label {
            color: #666;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .amount {
            text-align: right;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>E-Tiko Revenue Report</h1>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="summary">
        <h3>Revenue Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="summary-value">KSh {{ number_format($revenueData['total_revenue'], 2) }}</div>
                <div class="summary-label">Total Revenue</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $revenueData['total_bookings'] }}</div>
                <div class="summary-label">Total Bookings</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $revenueData['paid_bookings'] }}</div>
                <div class="summary-label">Paid Bookings</div>
            </div>
            <div class="summary-item">
                <div class="summary-value">{{ $revenueData['pending_bookings'] }}</div>
                <div class="summary-label">Pending Bookings</div>
            </div>
        </div>
    </div>

    <h3>Monthly Revenue Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Revenue (KSh)</th>
                <th>Percentage of Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($revenueData['monthly_breakdown'] as $month => $revenue)
            <tr>
                <td>{{ $month }}</td>
                <td class="amount">{{ number_format($revenue, 2) }}</td>
                <td class="amount">{{ number_format(($revenue / $revenueData['total_revenue']) * 100, 1) }}%</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background-color: #f8f9fa; font-weight: bold;">
                <td>Total</td>
                <td class="amount">{{ number_format($revenueData['total_revenue'], 2) }}</td>
                <td class="amount">100%</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>This report was generated by E-Tiko Event Management System</p>
    </div>
</body>
</html>
